### ISSUE TITLE
npm install on circle ci raise error

### ISSUE THREAD

**Issue by gatheluck** [gatheluck/cvpaperchallenge-homepage#10]
```
#!/bin/bash -eo pipefail
npm install
```

above command raises following error from 2021/02/04. this error is happened both workflow `build and deploy` and `nightly`.

```
TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/node-gyp/lib/index.js:2:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:4:55)
    at Module._compile (module.js:653:30)
/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163
      throw new Error('call config.load() before reading values')
      ^

Error: call config.load() before reading values
    at Config.get (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163:13)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:171:32)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)

Exited with code exit status 7
CircleCI received exit code 7
```

**Comment by gatheluck** [comment]
following looks related: https://github.com/npm/cli/issues/2599 .

**Comment by gatheluck** [comment]
above can not solve problem.
